cart/urls.py
from django.urls import path
from .views import add_cart, cart_delite, cart_detail,quantity_minus,quantity_plus,cart_delite

app_name = "cart"

urlpatterns = [
    path('add/<int:product_id>/', add_cart, name='add_cart'),
    path('', cart_detail, name='cart_detail'),
    path('plus/',quantity_plus, name='quantity_plus'),
    path('minus/', quantity_minus, name='quantity_minus'),
    path('delite/<int:id>', cart_delite, name="cart_delite")
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from config.settings import MEDIA_ROOT,MEDIA_URL
from django.conf.urls.static import static
# from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('user/',include('user.urls')),
    path('account/',include('django.contrib.auth.urls')),
    path('product/',include('product.urls')),
    path('cart/', include('cart.urls'))
]


urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('',Main.as_view(),name='main'),
    # path('<int:id>', Category_View.as_view(), name="category"),
    path('newproduct/', New_product.as_view(),name='new_product'),
    path('best/',Best.as_view(),name='best'),
    path('thriftyshopping/',Thrifty_shopping.as_view(),name='thrifty_shopping'),
    path('product/<int:id>/', Read_more, name='product'),
    path('search/', Search_fun, name='search')
    # path('prod_click/', Prod_click.as_view(), name="prod_click"),
    # path('category_id/', Cat_id.as_view(), name='category_id'),
]   

main/models.py
from django.db import models
from product.models import Product
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=32, help_text=u"category name")
    index = models.IntegerField(default=0, null=True, help_text=u"category 표시 순서 적을수록 위 순위")
    
    class Meta:
        db_table="Category"


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=32, help_text=u"subcategory name")
    index = models.IntegerField(default=0, null=True, help_text=u"subcategory 순서 적을수록 위 순위")

    class Meta:
        db_table="SubCategory"


class ShopProduct(models.Model):
    categorys = models.ManyToManyField(Category)
    sub_categorys = models.ManyToManyField(SubCategory)

    class Meta:
        db_table="ShopProduct"

        
class Category_id(models.Model):
    cat_id = models.IntegerField()

main/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from user.models import User
from product.models import Product
from main.models import Category, Category_id
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response
from django.db.models import Q
from django.contrib import messages
from django.utils import timezone
# @csrf_exempt

class Main(APIView):
    @csrf_exempt
    def get(self, request):
        product_object_list=Product.objects.all().order_by('-id')
        product_list=[]
        for product in product_object_list:
            product_list.append(dict(
                id = product.id,
                product_image = product.product_image,
                name= product.name,
                pro_seil_prace=product.pro_seil_prace,
                pro_seil_percent=product.pro_seil_percent,
                sell_price=product.sell_price,    
            ))
        email = request.session.get('email',None)

        user = User.objects.filter(email=email).first()
       
        return render(request, 'main/main.html',context=dict(
                                                products=product_list,
                                                user=user,
                                                ))


@csrf_exempt
def Search_fun(request):
        search_keyword = request.GET['q']
        search_product_list = Product.objects.filter(Q(name__icontains=search_keyword))
        context = {
            'search_keyword':search_keyword,
            'search_product_list':search_product_list
        }
        return render(request, 'main/search.html',context)
   


def Read_more(request,id):
    products = Product.objects.filter(id=id)
    email = request.session.get('email',None)
    user = User.objects.filter(email=email).first()
    return render(request, 'main/read_more.html', context=dict(products=products, user=user))


class New_product(APIView):
    @csrf_exempt
    def get(self, request):
        product_list = Product.objects.filter().order_by('-created_time')
        return render(request, 'main/new_product.html', context=dict(product_list=product_list))



class Best(APIView):
    def get(self, request):
        return render(request, 'main/best.html')


class Thrifty_shopping(APIView):
    @csrf_exempt
    def get(self, request):
        return render(request, 'main/thrifty_shopping.html')

templates/main/best.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
{% endblock style %}

{% block content %}
{% endblock content %}

templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<style>
    .slideshow-container {
        display: flex;
        width: 1515px;
        height: 400px;
        /* z-index: 0; */
    }

    .numbertext {
        color: #f2f2f2;
        font-size: 25px;
        padding: 20px 30px;
        position: absolute;
        top:65%;
        left: 65%;
    }

    .dot {
        cursor: pointer;
        height: 15px;
        width: 15px;
        margin: 0 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
        margin-top: 60px;
    }
    .active,
    .dot:hover {
        background-color: #717171;
    }
    .fade {
        animation-name: fade;
        animation-duration: 1.5s;
    }
    @keyframes fade {
        from {
            opacity: .4
        }

        to {
            opacity: 1
        }
    }

    @media only screen and (max-width: 300px) {
        .prev,
        .next,
        .text {
            font-size: 11px
        }
    }
     .product-container {
        display: flex;
        flex-direction:row;
        flex-wrap: wrap;
        max-width:1500px;
        height: 500px;
        justify-content:center;
        align-items:center;
        margin-bottom: 50px;
     }
     .product-1box{
        display: flex;
        flex-direction: column;
        justify-content: left;
        align-items: center;
        width: 300px;
        height: 500px;
        margin: 10px 5px 0 10px;
     }
     .img-container{
        position:relative;
        display: flex;
        flex-direction: column;
        top: 10%;
        width: 300px; 
        margin: 10px 5px 0 10px;
        width: 300px;
        height: 350px;
     }
     .img{
        width:100%; 
        height:100%; 
        object-fit:cover
        
    }
    .price-box {
        display: flex; 
        width:100% ;
        height: 30px;
        flex-direction:column;
        margin-top: 60px;
     }
    .product-price{
        display:flex; 
        flex-direction:column;
     }
    .cart-button{
        position:absolute; 
        left: 80%; 
        top:85%; 
        background-color:rgb(243, 243, 243);
        width: 45px;
        height: 45px;
        border-color: blueviolet; 
        border-radius: 30px;
    }
    .scroll-nev-bar {
        display: none;
        background-color: white;
        width: 1515px;
        flex-direction: row;
        justify-content: space-between;
        position: fixed;
        margin-bottom: 20px;
        z-index: 888;
        top: 0;
    }
</style>
{% endblock style %}

{% block content %}
<!-- 광고 사진 시작 -->
<div style="display: flex;flex-direction:column; padding-top: 10px;">
    <div class="slideshow-container">
        <div class="mySlides fade">
            <div class="numbertext">1 / 3</div>
            <img src="https://product-image.kurly.com/cdn-cgi/image/format=auto/banner/main/pc/img/201943aa-6771-4163-aa23-6d34f006c2a9.jpg"
                style="width:100%;height:400px">
        </div>

        <div class="mySlides fade">
            <div class="numbertext">2 / 3</div>
            <img src="https://product-image.kurly.com/cdn-cgi/image/format=auto/banner/main/pc/img/eb91e8cc-fad1-4190-b7e8-0224ed02d6fa.jpg"
                style="width:100%;height:400px">
        </div>

        <div class="mySlides fade">
            <div class="numbertext">3 / 3</div>
            <img src="https://product-image.kurly.com/cdn-cgi/image/format=auto/banner/main/pc/img/813f5567-9482-4b4a-b040-f38b6deabf1b.png" style="width:100%;height:400px">
        </div>
    </div>
</div>
<!-- 파매 물겅 시작 -->
<div>
    <div style="display: flex;justify-content: center;align-items: center;margin-top: 30px; ">
        <h2>이 상품 어때요?</h2>
    </div>
    <div class="product-container">
        {% for product in products %}
        <a style="text-decoration: none; color:black" href="{% url 'product' product.id %}">
            <div class="product-1box">
                <div class="img-container">
                    <img id="{{product.id}}" class="img" src="{% get_media_prefix %}{{ product.product_image }}" alt="상품 이미지">
                    <button class="cart-button" type="button">
                        <img style="width: 100%;"
                            src="https://as2.ftcdn.net/v2/jpg/03/36/55/77/1000_F_336557716_Wc8izQSoR68N2JgMRnwTuZ3PeDzsyVUK.jpg"
                            alt="">
                    </button>
                </div>
                <div class="price-box">
                    <div class="product-name;">
                        <h5>{{ product.name }} </h5>
                    </div>
                    <div class="product-price">
                        <div style="display:flex; flex-direction:column;">
                            {% load humanize %}
                            {% if product.pro_seil_prace %}
                            <div style="display: flex; flex-direction:row;">
                                <span style="color: red;"><b>{{product.pro_seil_percent}}%</b></span>
                                <span style="margin-left: 20px;"> <b>{{ product.sell_price|intcomma }} 원</b></span>
                            </div>
                            <span style="text-decoration: line-through;">{{product.pro_seil_prace|intcomma}} 원</span>    
                            {% else %}
                            <span> <b>{{ product.sell_price|intcomma }} 원</b></span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
<!-- 판매 물건 끝 -->
<script>
    let slideIndex = 0;
    showSlides();
    function showSlides() {
        let i;
         slides = document.getElementsByClassName("mySlides");
        // var dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) { slideIndex = 1 }
        // for (i = 0; i < dots.length; i++) {
        //     dots[i].className = dots[i].className.replace(" active", "");
        // }
        slides[slideIndex - 1].style.display = "block";
        // dots[slideIndex - 1].className += " active";
        setTimeout(showSlides, 2000); // Change image every 2 seconds
    }
</script>
{% endblock content %} 

templates/main/new_product.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<style>
     .product-container {
        display: flex;
        flex-direction:row;
        flex-wrap: wrap;
        max-width:1500px;
        height: 500px;
        justify-content:center;
        align-items:center;
        margin-bottom: 50px;
     }
     .product-1box{
        display: flex;
        flex-direction: column;
        justify-content: left;
        align-items: center;
        width: 300px;
        height: 500px;
        margin: 10px 5px 0 10px;
     }
     .img-container{
        position:relative;
        display: flex;
        flex-direction: column;
        top: 10%;
        width: 300px; 
        margin: 10px 5px 0 10px;
        width: 300px;
        height: 350px;
     }
     .img{
        width:100%; 
        height:100%; 
        object-fit:cover
        
    }
    .price-box {
        display: flex; 
        width:100% ;
        height: 30px;
        flex-direction:column;
        margin-top: 60px;
     }
    .product-price{
        display:flex; 
        flex-direction:column;
     }
    .cart-button{
        position:absolute; 
        left: 80%; 
        top:85%; 
        background-color:rgb(243, 243, 243);
        width: 45px;
        height: 45px;
        border-color: blueviolet; 
        border-radius: 30px;
    }
    .scroll-nev-bar {
        display: none;
        background-color: white;
        width: 1515px;
        flex-direction: row;
        justify-content: space-between;
        position: fixed;
        margin-bottom: 20px;
        z-index: 888;
        top: 0;
    }
</style>
{% endblock style %}

{% block content %}
<div>
    <div style="display: flex;justify-content: center;align-items: center;margin-top: 30px; ">
        <h2>신상품</h2>
    </div>
    <div class="product-container">
        {% for product in product_list %}
        <a style="text-decoration: none; color:black" href="{% url 'product' product.id %}">
            <div class="product-1box">
                <div class="img-container">
                    <img id="{{product.id}}" class="img" src="{% get_media_prefix %}{{ product.product_image }}">
                    <button class="cart-button" type="button">
                        <img style="width: 100%;"
                            src="https://as2.ftcdn.net/v2/jpg/03/36/55/77/1000_F_336557716_Wc8izQSoR68N2JgMRnwTuZ3PeDzsyVUK.jpg"
                            alt="">
                    </button>
                </div>
                <div class="price-box">
                    <div class="product-name;">
                        <h5>{{ product.name }} </h5>
                    </div>
                    <div class="product-price">
                        <div style="display:flex; flex-direction:column;">
                            {% load humanize %}
                            {% if product.pro_seil_prace %}
                            <div style="display: flex; flex-direction:row;">
                                <span style="color: red;"><b>{{product.pro_seil_percent}}%</b></span>
                                <span style="margin-left: 20px;"> <b>{{ product.sell_price|intcomma }} 원</b></span>
                            </div>
                            <span style="text-decoration: line-through;">{{product.pro_seil_prace|intcomma}} 원</span>    
                            {% else %}
                            <span> <b>{{ product.sell_price|intcomma }} 원</b></span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/main/read_more.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<style>
    .product_continer{
        display: flex;
        justify-content: center;
        width: 1519px;
        height: 1500px;
        background-color:whitesmoke;
        padding-top: 30px;
        cursor: default;
    }
    .pro_cont_in {
        display: flex;
        flex-direction: row;
        width: 70%;
        height: 100%;
        background-color:whitesmoke;
    }
    .product_img_cont{
        display: block;
        left: 48%;
        width: 40%;
        height: 550px;
        background-color: whitesmoke;
    }
    .product_img_cont img {
        height: 100%;
        width: 100%;
    }
    .empty_cont {
        display: flex;
        width: 8%;
        background-color: whitesmoke;
    }
    .product_price_cont{
        display: block;
        flex-direction: column;
        right: 52%;
        width: 52%;
        height: 670px;
        background-color: whitesmoke;
    }
    .product_name{
        display: flex;
        padding-top: 20px;
        font-size: 20px;
        font-weight: bolder;
    }
    .product_explanation{
        font-weight: 100px;
        padding-top: 10px;
        font-size: small;
        opacity: 70%;
    }
    .product_price{
        display: flex;
        flex-direction: row;
        font-weight: bolder;
        font-size: 30px;
        padding-top: 10px;
    }
    .is_login h6{
        font-size: 14px;
        color:rgb(83, 7, 149);
    }
    .product_shipping{
        display: flex;
        flex-direction: row;
        width: 100%;
        height: 50px;
    }
    .product_seller{
        display: flex;
        flex-direction: row;
        width: 100%;
        height: 30px;
    }
    .product_notification{
        display: flex;
        flex-direction: row;
        width: 100%;
        height: 80px;
    }
    .left_box{
        width: 200px;
        padding-right: 50px;
        font-size: 15px;
    }
    .right_boxs{
        display: flex;
        flex-direction: column;
        border: 1px solid;
        width: 400px;
        height: 80px;
        /* border-width: 100px; */
    }
    .right_boxs div{
        /* padding-top: px; */
        font-size: small;
    }
    .prod_total_amount{
        display: flex;
        flex-direction: row;
        align-items: center;
        width: 670px;
        padding-left:330px;
        font-weight: bolder;
        font-size: 30px;
    }
    .prod_total_amount div{
        padding-left: 10px;
    }
    .cart_button_continer{
        display: flex;
        flex-direction: row;
        padding-top: 20px;
    }
    .favorite_box{
        display:flex;
        padding-right: 10px;
        border: 1px dotted;
        justify-content: center;
        align-items: center;
        width: 50px;
        height: 50px;
        cursor: pointer;
    }
    .notifications_box{
        display:flex;
        padding-right: 10px;
        border: 1px dotted;
        justify-content: center;
        align-items: center;
        width: 50px;
        height: 50px;
        cursor: pointer;
    }
    #total_amount_sell_price{
        border:none; 
        background-color:whitesmoke;
        cursor: default;
    }
    .add_remove_amount{
        width:120px; 
        height: 40px ;
        display: flex; 
        justify-content: space-around;
        align-items: center;
    }
</style>
{% endblock style %}

{% block content %}
{% for product in products%}
<div class="product_continer">
    <div class="pro_cont_in">
        <div class="product_img_cont">
            <img src="{% get_media_prefix %}{{ product.product_image }}" alt="상품 이미지">
        </div>
        <div class="empty_cont"></div>
        <div class="product_price_cont">
            <div class="product_name">
                <div>{{product.name}}</div>
            </div>
            <div class="product_explanation">  
                {{product.pro_manual}}
            </div>
            <div class="product_price">
                {% load humanize %}
                {% if product.pro_seil_prace %}
                <span style="color: red;padding-right: 15px;">{{product.pro_seil_percent}}%</span>
                <span>{{product.sell_price|intcomma}}원</span>
                {% else %}
                <span>{{product.sell_price|intcomma}}원</span>
                {% endif %}
            </div>
            <span style="text-decoration:line-through;opacity:0.5;font-size:15px">{{ product.pro_seil_prace|intcomma }}원</span>
            {% if user is None %}
            <div class="is_login">
                <h6>로고인후, 적닙 혜택이 제공됩니다</h6>
            </div>
            {% else %}

            {% endif %}
            <hr>
            <div class="product_shipping">
                <div class="left_box">
                    배송
                </div>
                <div class="right_box">
                    샛별배송
                </div>
            </div>
            <hr>
            <div class="product_seller">
                <div class="left_box">
                    판매자
                </div>
                <div class="right_box">
                    HoMeShOpInG
                </div>
            </div>
            <hr>
            <div class="product_seller">
                <div class="left_box">
                    포장타입
                </div>
                <div class="right_box">
                    냉장
                </div>
            </div>
            <hr>
            <div class="product_seller">
                <div class="left_box">
                    판매단위
                </div>
                <div class="right_box">
                    1팩
                </div>
            </div>
            <hr>
            <div class="product_seller">
                <div class="left_box">
                    중량/용량
                </div>
                <div class="rigth_box">
                    300g/500g
                </div>
            </div>
            <hr>
            <div class="product_seller">
                <div class="left_box">
                    원산지
                </div>
                <div>
                    상세페이지 별도표기
                </div>
            </div>
            <hr>
            <div class="product_notification">
                <div class="left_box">
                    안내사항
                </div>
                <div class="rigth_box">
                    -해당 상품은 냉장 상품입니다.<br>
                    -상품 수령 후 최대한 빠른 실내에 섭취를 권장드립니다..
                </div>
            </div>
            <hr>
            <div class="product_notification">
                <div class="left_box">
                    구매수량
                </div>
                <div class="right_boxs">
                    <div>
                       종량/용량 
                    </div>
                    <div style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;padding-top: 10px;">
                        <div class="add_remove_amount updown">
                            <span class="material-symbols-outlined product_remove">remove</span>
                            <input type="submit" name="p_num1" id="product_number" class="p_num1" autocomplete="off" value="1">
                            <span class="material-symbols-outlined product_add">add</span>
                        </div>
                        <span style="text-decoration:line-through;opacity:0.5;font-size:15px;padding-left: 100px;">{{ product.pro_seil_prace|intcomma }}원</span>
                        <div style="font-weight:bolder; font-size:medium">
                            <input class="sell_price" type="submit" id="total_amount_sell_price" name="sell_price" value="{{product.sell_price|intcomma}}">원
                        </div>
                    </div>
                </div>  
            </div>
            <hr>
            <div class="prod_total_amount">
                <h6>총 상품금액:</h6>
                <input class="total_amount" type="submit" id="total_amount_sell_price" name="sum" value="{{product.sell_price|intcomma}}" readonly>원
            </div>
            <div class="cart_button_continer">
                <div class="favorite_box">
                    <span id="favorite" style="padding-left: 6px; font-size: 30px; color: red;" class="material-icons-outlined">favorite_border</span>
                </div>
                <div class="notifications_box">
                    <span style="padding-left: 6px;font-size: 30px;color: rgb(97, 14, 176);" class="material-symbols-outlined">notifications</span>
                </div>
                <a href="{% url 'cart:add_cart' product.id %}"><button style="width: 455px; height: 50px;" id="cart_add_button" type="button" class="btn btn-success">장바구니에 담기</button></a>
            </div>
        </div>
    </div>
</div>

<script>
    $("#favorite").click(function(){
        if($('#favorite').html() == "favorite_border"){
            $('#favorite').html("favorite")
        }else{
            $('#favorite').html("favorite_border")
        }
    })
    $('#cart_add_button').click(function () {
        let quantity = $('#product_number').val()
        $.ajax({
            url: "{% url 'cart:add_cart' product.id %}",
            data: {
                quantity: quantity,
            },
            method: "POST",
            success: function (data) {
                console.log("성공");
            },
            error: function (request, status, error,) {
                console.log("에러");
            },
            complete: function () {
                console.log("완료");
            }
        });
    })


    $('.product_add').click(function () {
        let number = $('#product_number').val()
        let sell_price = "{{product.sell_price}}"
        let n = 1
        if (number >= 1) {
            new_nam = parseInt(number) + n
            sum_price = new_nam * sell_price
            sum_price2 = sum_price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
            $('.total_amount').val(sum_price2)
            $('#product_number').val(new_nam)
        }
    });
    
    $('.product_remove').click(function () {
        let number = $('#product_number').val()
        let sell_price = "{{product.sell_price}}"
        let n = 1
        if (number > 1) {
            new_nam = parseInt(number) - n
            sum_price = new_nam * sell_price
            sum_price = new_nam * sell_price
            sum_price2 = sum_price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
            $('.total_amount').val(sum_price2)
            $('#product_number').val(new_nam)
        }
    });
</script>
{% endfor %}   
{% endblock content %}

templates/main/search.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
<style>
    .product-container {
        display: flex;
        flex-direction:row;
        flex-wrap: wrap;
        max-width:1500px;
        height: 500px;
        justify-content:center;
        align-items:center;
        margin-bottom: 50px;
     }
     .product-1box{
        display: flex;
        flex-direction: column;
        justify-content: left;
        align-items: center;
        width: 300px;
        height: 500px;
        margin: 10px 5px 0 10px;
     }
     .img-container{
        position:relative;
        display: flex;
        flex-direction: column;
        top: 10%;
        width: 300px; 
        margin: 10px 5px 0 10px;
        width: 300px;
        height: 350px;
     }
     .img{
        width:100%; 
        height:100%; 
        object-fit:cover
        
    }
    .price-box {
        display: flex; 
        width:100% ;
        height: 30px;
        flex-direction:column;
        margin-top: 60px;
     }
    .product-price{
        display:flex; 
        flex-direction:column;
     }
    .cart-button{
        position:absolute; 
        left: 80%; 
        top:85%; 
        background-color:rgb(243, 243, 243);
        width: 45px;
        height: 45px;
        border-color: blueviolet; 
        border-radius: 30px;
    }
</style>
{% endblock style %}

{% block content %}
<div style="display: flex; flex-direction: column; width: 100%; height: 100%;background-color:white;">
    <div style="display: flex;justify-content: center;align-items: center;margin-top: 30px; ">
        {% if not search_product_list %}
            <h1><h3 style="color:blueviolet">'{{search_keyword}}'</h3>에 대한 검색결과가 없음!</h1>
        {% else %}
            <h1><h3 style="color:blueviolet">'{{search_keyword}}'</h3>에 대한 검색결과가!</h1>
        {% endif %}
    </div>
    <div class="product-container">
        {% for search_product in search_product_list %}
        <a style="text-decoration: none; color:black" href="{% url 'product' search_product.id %}">
            <div class="product-1box">
                <div class="img-container">
                    <img id="{{product.id}}" class="img" src="{% get_media_prefix %}{{ search_product.product_image }}">
                    <button class="cart-button" type="button">
                        <img style="width: 100%;"
                            src="https://as2.ftcdn.net/v2/jpg/03/36/55/77/1000_F_336557716_Wc8izQSoR68N2JgMRnwTuZ3PeDzsyVUK.jpg"
                            alt="">
                    </button>
                </div>
                <div class="price-box">
                    <div class="product-name;">
                        <h5>{{ search_product.name }}</h5>
                    </div>
                    <div class="product-price">
                        <div style="display:flex; flex-direction:column;">
                            {% load humanize %}
                            {% if search_product.pro_seil_prace %}
                            <div style="display: flex; flex-direction:row;">
                                <span style="color: red;"><b>{{search_product.pro_seil_percent}}%</b></span>
                                <span style="margin-left: 20px;"> <b>{{ search_product.sell_price|intcomma }} 원</b></span>
                            </div>
                            <span style="text-decoration: line-through;">{{search_product.pro_seil_prace|intcomma}} 원</span>    
                            {% else %}
                            <span> <b>{{ search_product.sell_price|intcomma }} 원</b></span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}   

templates/main/thrifty_shopping.html
{% extends 'main/base.html' %}
{% load static %}
{% block style %}
{% endblock style %}

{% block content %}
{% endblock content %}